export const endpoints = {
  health: "/health",
  auth: {
    login: "/auth/login",
    register: "/auth/register",
    me: "/auth/me",
    logout: "/auth/logout",
  },
  categories: "/categories",
  products: "/products",
  adminProducts: "/admin/products",
  adminCategories: "/admin/categories",
  adminDashboard: {
    summary: "/admin/dashboard/summary",
    sales: "/admin/dashboard/sales",
    ordersByStatus: "/admin/dashboard/orders-by-status",
    lowStock: "/admin/dashboard/low-stock",
  },
  addresses: "/addresses",
  cart: "/cart",
  orders: "/orders",
  payments: "/payments",
  adminPayments: "/admin/payments",
  inventoryLogs: "/admin/inventory/logs",
  adminOrders: "/admin/orders",
  adminShipments: "/admin/shipments",
  adminVariants: "/admin/variants",
  adminProductImages: "/admin/products",
  shipments: "/shipments",
} as const;
